project_id = "cdzpjecauzedmcwojtpo"

[functions.check-port]
verify_jwt = false

[functions.error-solver]
verify_jwt = false

[functions.docker-ask]
verify_jwt = false

[functions.git-ask]
verify_jwt = false

